### ISSUE TITLE
can not run

### ISSUE THREAD

**Issue by BenxiaHu** [pritykinlab/InterDomain#1]
`call_metadomains_intra -h`
Traceback (most recent call last):
  File "/data/anaconda3/envs/python312/bin/call_metadomains_intra", line 5, in <module>
    from InterDomain.cli_intra import main_cli_intra
  File "/data/anaconda3/envs/python312/lib/python3.12/site-packages/InterDomain/__init__.py", line 1, in <module>
    from .processing import main
ModuleNotFoundError: No module named 'InterDomain.processing'

**Comment by gdolsten** [comment]
Hey, I didn't get this notification for some reason. This is now fixed. Let me know what is your use case and I can help you run through it
